=== mpan322/CCS1006Eliza/Eliza/src/scripts/script-schema.json
{
    "$id": "./script-schema",
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "",
    "description": "",
    "type": "object",

    "properties": {
        
        "main-script" : {
            "type" : "array",
            "items": { 

                "type" : "object",
                "properties": {
                    "keyword" : {
                        "type" : "string"
                    },
                    "priority" : {
                        "type" : "integer"
                    },
                    "decompositon-rules" : {
                        "type": "array",
                        "items": {
                            "type" : "object",
                            "properties" : {
                                "pattern" : {
                                    "type" : "string"
                                },
                                "reassembly-rules" : {
                                    "type" : "array",
                                    "items": {
                                        "type" : "string"
                                    },                    
                                    "minItems" : 1            
                                }
                            },
                            "required": ["pattern", "reassembly-rules"]
                        },
                        "minItems" : 1
                    }
                },

                "minItems" : 1,

                "required": ["keyword", "priority", "decompositon-rules"]
            }
        },

        "pre-substitutions" : {
            "type" : "array",
            "items": {
                "type" : "object",
                "properties": {
                    "input" : {
                        "type" : "string"
                    },
                    "replacement" : {
                        "type" : "string"
                    }
                },
                "required": ["input", "replacement"]
            }
        },

        "post-substitutions" : {
            "type" : "array",
            "items": {
                "type" : "object",
                "properties": {
                    "input" : {
                        "type" : "string"
                    },
                    "replacement" : {
                        "type" : "string"
                    }
                },
                "required": ["input", "replacement"]
            }
        },

        "quit-keywords" : {
            "type" : "array",
            "items": {
                "type" : "string"
            }
        },
    
        "welcome-message" : {
            "type" : "string"
        },
        "final-message" : {
            "type" : "string"
        }

    },

    "required": ["main-script", "pre-substitutions", "quit-keywords", "post-substitutions", "welcome-message", "final-message"]

}

=== mpan322/CCS1006Eliza/Eliza/src/scripts/script.json
{   
    "$schema": "./script-schema.json",
    "welcome-message": "Hey!",
    "final-message": "Goodbye.",
    "quit-keywords": ["quit", "bye"],
    "main-script": [
        {
            "keyword": "feel",
            "priority": 1,
            "decompositon-rules": [
                {
                    "pattern": "I feel *",
                    "reassembly-rules": [
                        "Why do youn feel 1?"
                    ]                    
                }
            ]
        },
        {
            "keyword": "hello",
            "priority": 2,
            "decompositon-rules": [
                {
                    "pattern": "hello how are you?",
                    "reassembly-rules": [
                        "I am good! And you?"
                    ]
                }
            ]
        }
    ],
    "pre-substitutions": [
        {
            "input": "I",
            "replacement": "you"
        }
    ],

    "post-substitutions": [
        {
            "input": "hello",
            "replacement": "goodbye"
        }
    ]

}
